[tool.ruff]
line-length = 100
extend-exclude = [
    "__pycache__",
    ".git",
    ".github",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "*.egg-info",
]

# Ignorer les erreurs communes dans le code existant
ignore = [
    "F841",  # Local variable is assigned to but never used
    "E402",  # Module level import not at top of file
    "B011",  # Do not assert False
    "F821",  # Undefined name
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
kwargs-delimiter = "consistent"
