name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install pre-commit
          pip install uv
      - name: Run pre-commit hooks
        run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Create test environment file
        run: |
          cat > .env.test << EOF
          # Variables d'environnement factices pour les tests CI
          SUPABASE_URL=https://example.supabase.co
          SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlc3QiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTY0MjA3MTU5OCwiZXhwIjoxOTU3NjQ3NTk4fQ.test_key
          POSTGRES_SERVER=localhost
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
          POSTGRES_DB=app_test
          FIRST_SUPERUSER=admin@example.com
          FIRST_SUPERUSER_PASSWORD=admin12345
          EOF
          
          echo "Created .env.test file with test variables"
          cat .env.test
      - name: Install dependencies
        run: |
          pip install uv
          # Créer un environnement virtuel
          uv venv
          source .venv/bin/activate
          # Installer les dépendances
          uv pip install pytest pytest-cov
          cd backend
          uv pip install -e .
      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          cd backend
          pytest --cov=app --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./backend/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Check if Dockerfile exists
        id: check_dockerfile
        run: |
          if [ -f "Dockerfile" ]; then
            echo "dockerfile_exists=true" >> $GITHUB_OUTPUT
          else
            echo "dockerfile_exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Build Docker image
        if: steps.check_dockerfile.outputs.dockerfile_exists == 'true'
        run: docker build -t fastapi-supabase-template:${{ github.sha }} .
      - name: Skip Docker build
        if: steps.check_dockerfile.outputs.dockerfile_exists != 'true'
        run: echo "Skipping Docker build because Dockerfile doesn't exist at the root directory"
