name: Run Python Script and Update README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0
          token: ${{ secrets.ATTICUS_PAT }}

      - name: Configuring git credentials
        run: |
          git config --global user.email "1831768457@qq.com"
          git config --global user.name "Atticuszz"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install useful-scripts

      - name: Run the script for recently modified
        run: markdown --root ${{ github.workspace }} modify_recent --output ${{ github.workspace }}/README.md --num_commits 50 --dir src --title "### Latest Changes"


      - name: Commit README changes
        run: |
          git add README.md
          git commit -m "chore: update README.md" || echo "No changes to commit"
          git push origin main
